ADAPT-8912 - react version of text input
adaptlearning/adapt-contrib-textInput pull request #109
Opened 2022-01-31 15:10 UTC by eleanor-heath

https://github.com/adaptlearning/adapt-contrib-textInput/issues/110

2022-01-31 15:54 UTC, cahirodoherty-learningpool approved these changes
👀

2022-02-02 15:43 UTC, lc-alexanderbenesch approved these changes
👍

2022-02-07 12:57 UTC, joe-allen-89 approved these changes
👍

2022-02-21 11:49 UTC, oliverfoster requested changes

2022-02-21 11:49 UTC, oliverfoster commented on templates/textinput.jsx
> +  const shouldShowMarking = isInteractive() && _canShowMarking;
Can use `_shouldShowMarking` straight from the model

2022-02-23 17:07 UTC, oliverfoster commented
Just waiting for https://github.com/adaptlearning/adapt-contrib-core/pull/68 to be merged and released.

2022-03-07 15:40 UTC, merged